#!/system/bin/sh

echo space | ./hid-gadget-test /dev/hidg1 keyboard

sleep 1.5 | ./hid-gadget-test /dev/hidg1 keyboard

echo 1 4 7 9 3 5 7 9 0 4 2| ./hid-gadget-test /dev/hidg1 keyboard

echo enter | ./hid-gadget-test /dev/hidg1 keyboard

sleep 1.5

echo 8 2 4 6 3 4 5 9 0 6 5 0 | ./hid-gadget-test /dev/hidg1 keyboard

sleep 1.0

echo enter | ./hid-gadget-test /dev/hidg1 keyboard

sleep 1.0

echo 6 1 0 3 5 4 8 5 0 4 8 6 4 | ./hid-gadget-test /dev/hidg1 keyboard

echo enter | ./hid-gadget-test /dev/hidg1 keyboard

8sleep 1.0

echo 5 7 2 9 6 0 3 6 5 7 | ./hid-gadget-test /dev/hidg1 keyboard

echo enter | ./hid-gadget-test /dev/hidg1 keyboard

sleep 1.0

echo 2 1 7 0 | ./hid-gadget-test /dev/hidg1 keyboard

echo enter | ./hid-gadget-test /dev/hidg1 keyboard

sleep 3.0

echo w a | ./hid-gadget-test /dev/hidg1 keyboard

echo period | ./hid-gadget-test /dev/hidg1 keyboard

echo l i n k | ./hid-gadget-test /dev/hidg1 keyboard

echo slash | ./hid-gadget-test /dev/hidg1 keyboard

echo  p 3 9 z a p | ./hid-gadget-test /dev/hidg1 keyboard

sleep 3.0 | ./hid-gadget-test /dev/hidg1 keyboard

echo i p é : | ./hid-gadget-test /dev/hidg1 keyboard

echo 1 7 7 . 1 7 7 . 1 7 7 | ./hid-gadget-test /dev/hidg1 keyboard
