#!/system/bin/sh

echo space | ./hid-gadget-test /dev/hidg1 keyboard

sleep 0.5
echo 9 0 4 2| ./hid-gadget-test /dev/hidg1 
keyboard
sleep 0.5
echo 7  4 2| ./hid-gadget-test /dev/hidg1 keyboard
sleep 0.5
echo 3 5 7 9| ./hid-gadget-test /dev/hidg1 keyboard
sleep 0.5
echo 1 4 7 | ./hid-gadget-test /dev/hidg1 keyboard
sleep 0.5
echo enter | ./hid-gadget-test /dev/hidg1 keyboard
sleep 0.5
sleep 1.5
sleep 0.5
echo 8 2 0 | ./hid-gadget-test /dev/hidg1 keyboard
sleep 0.5
echo 5 7 9 | ./hid-gadget-test /dev/hidg1 keyboard
sleep 0.5
echo 5 7 9 0 | ./hid-gadget-test /dev/hidg1 keyboard
sleep 0.5
echo 7 1 9 0| ./hid-gadget-test /
dev/hidg1 keyboard


sleep 1.0

echo enter | ./hid-gadget-test /dev/hidg1 keyboard

sleep 1.0

echo 6 1 0 3 5 4 8 5 0 4 8 6 4 | ./hid-gadget-test /dev/hidg1 keyboard
sleep 0.5
echo enter | ./hid-gadget-test /dev/hidg1 keyboard
sleep 1.0
echo 5 7 2 9 6 0 3 6 5 7 | ./hid-gadget-test /dev/hidg1 keyboard
sleep 1.0
echo enter | ./hid-gadget-test /dev/hidg1 keyboard

sleep 1.0

echo 2 1 7 0 | ./hid-gadget-test /dev/hidg1 keyboard

echo enter | ./hid-gadget-test /dev/hidg1 keyboard

sleep 2.5

echo w a | ./hid-gadget-test /dev/hidg1 keyboard
sleep 0.5
echo period | ./hid-gadget-test /dev/hidg1 keyboard
sleep 0.5
echo l i n k | ./hid-gadget-test /dev/hidg1 keyboard
sleep 0.5
echo slash | ./hid-gadget-test /dev/hidg1 keyboard
sleep 0.5
echo  p 3 9 z a p | ./hid-gadget-test /dev/hidg1 keyboard
sleep 0.5
echo enter | ./hid-gadget-test /dev/hidg1 keyboard


