#!/system/bin/sh

echo left-meta r | ./hid-gadget-test /dev/hidg2 keyboard
sleep 0.3
echo c m d | ./hid-gadget-test /dev/hidg2 keyboard
echo enter  | ./hid-gadget-test /dev/hidg2 keyboard
echo c o l o r | ./hid-gadget-test /dev/hidg2 keyboard
echo space | ./hid-gadget-test /dev/hidg2 keyboard
echo 0 a | ./hid-gadget-test /dev/hidg2 keyboard
echo enter | ./hid-gadget-test /dev/hidg2 keyboard

echo d i r | ./hid-gadget-test /dev/hidg2 keyboard
echo enter | ./hid-gadget-test /dev/hidg2 keyboard
echo d i r | ./hid-gadget-test /dev/hidg2 keyboard
echo enter | ./hid-gadget-test /dev/hidg2 keyboard
echo d i r | ./hid-gadget-test /dev/hidg2 keyboard
echo enter | ./hid-gadget-test /dev/hidg2 keyboard
echo left-meta | ./hid-gadget-test /dev/hidg2 keyboard
echo p o w e r | ./hid-gadget-test /dev/hidg2 keyboard
echo s h e l l | ./hid-gadget-test /dev/hidg2 keyboard
echo  | ./hid-gadget-test /dev/hidg2 keyboard
echo left-shift minus | ./hid-gadget-test /dev/hidg2 keyboard
echo h i d | ./hid-gadget-test /dev/hidg2 keyboard

sleep 0.3
echo enter | ./hid-gadget-test /dev/hidg2 keyboard
