#!/system/bin/sh

echo left-meta r | ./hid-gadget-test /dev/hidg1 keyboard
sleep 0.3
echo c m d | ./hid-gadget-test /dev/hidg1 keyboard
echo enter  | ./hid-gadget-test /dev/hidg1 keyboard
sleep 1.0
echo c o l o r | ./hid-gadget-test /dev/hidg1 keyboard
echo space | ./hid-gadget-test /dev/hidg1 keyboard
echo 0 a | ./hid-gadget-test /dev/hidg1 keyboard
echo enter | ./hid-gadget-test /dev/hidg1 keyboard
echo d i r | ./hid-gadget-test /dev/hidg1 keyboard 
echo enter | ./hid-gadget-test /dev/hidg1 keyboard
sleep 0.3
echo i p c o n f | ./hid-gadget-test /dev/hidg1 keyboard
echo i g | ./hid-gadget-test /dev/hidg1 keyboard
echo enter | ./hid-gadget-test /dev/hidg1 keyboard
sleep 0.5
echo left-meta | ./hid-gadget-test /dev/hidg1 keyboard
sleep 0.7
echo p o w e r | ./hid-gadget-test /dev/hidg1 keyboard
echo s h e l l | ./hid-gadget-test /dev/hidg1 keyboard
sleep 0.2
echo right | ./hid-gadget-test /dev/hidg1 keyboard
sleep 0.2
echo down | ./hid-gadget-test /dev/hidg1 keyboard
sleep 0.2
echo enter | ./hid-gadget-test /dev/hidg1 keyboard
sleep 1.0
echo left | ./hid-gadget-test /dev/hidg1 keyboard
echo enter | ./hid-gadget-test /dev/hidg1 keyboard
sleep 0.5
echo h e l p | ./hid-gadget-test /dev/hidg1 keyboard
echo enter | ./hid-gadget-test /dev/hidg1 keyboard
sleep 0.5
echo left-meta r | ./hid-gadget-test /dev/hidg1 keyboard
sleep 0.3
echo h t t p | ./hid-gadget-test /dev/hidg1 keyboard
echo down | ./hid-gadget-test /dev/hidg1 keyboard
echo down | ./hid-gadget-test /dev/hidg1 keyboard
echo down | ./hid-gadget-test /dev/hidg1 keyboard
echo enter  | ./hid-gadget-test /dev/hidg1 keyboard
sleep 5.0
echo left-meta r | ./hid-gadget-test /dev/hidg1 keyboard
sleep 0.3
echo c m d | ./hid-gadget-test /dev/hidg1 keyboard
echo enter  | ./hid-gadget-test /dev/hidg1 keyboard
sleep 1.0
echo t a s k l i s t  | ./hid-gadget-test /dev/hidg1 keyboard
echo enter  | ./hid-gadget-test /dev/hidg1 keyboard
echo f11  | ./hid-gadget-test /dev/hidg1 keyboard
sleep 0.2
echo f11  | ./hid-gadget-test /dev/hidg1 keyboard
echo t a s k k i l l  | ./hid-gadget-test /dev/hidg1 keyboard
echo space  | ./hid-gadget-test /dev/hidg1 keyboard
echo / f  | ./hid-gadget-test /dev/hidg1 keyboard
echo space  | ./hid-gadget-test /dev/hidg1 keyboard
echo / i m  | ./hid-gadget-test /dev/hidg1 keyboard
echo space  | ./hid-gadget-test /dev/hidg1 keyboard
echo c h r o m e . e x e  | ./hid-gadget-test /dev/hidg1 keyboard
echo enter  | ./hid-gadget-test /dev/hidg1 keyboard
echo t a s k k i l l  | ./hid-gadget-test /dev/hidg1 keyboard
echo space  | ./hid-gadget-test /dev/hidg1 keyboard
echo / f  | ./hid-gadget-test /dev/hidg1 keyboard
echo space  | ./hid-gadget-test /dev/hidg1 keyboard
echo / i m  | ./hid-gadget-test /dev/hidg1 keyboard
echo space  | ./hid-gadget-test /dev/hidg1 keyboard
echo c m d . e x e  | ./hid-gadget-test /dev/hidg1 keyboard




