#!/system/bin/sh

echo left-meta r | ./hid-gadget-test /dev/hidg2 keyboard
sleep 0.3
echo c m d | ./hid-gadget-test /dev/hidg2 keyboard
echo enter  | ./hid-gadget-test /dev/hidg2 keyboard
echo c o l o r | ./hid-gadget-test /dev/hidg2 keyboard
echo space | ./hid-gadget-test /dev/hidg2 keyboard
echo 0 a | ./hid-gadget-test /dev/hidg2 keyboard
echo enter | ./hid-gadget-test /dev/hidg2 keyboard

echo d i r \ s | ./hid-gadget-test /dev/hidg2 keyboard 
echo enter | ./hid-gadget-test /dev/hidg2 keyboard
sleep 3.5
echo left-meta | ./hid-gadget-test /dev/hidg2 keyboard
echo p o w e r | ./hid-gadget-test /dev/hidg2 keyboard
echo s h e l l | ./hid-gadget-test /dev/hidg2 keyboard
echo right | ./hid-gadget-test /dev/hidg2 keyboard
echo down | ./hid-gadget-test /dev/hidg2 keyboard
echo enter | ./hid-gadget-test /dev/hidg2 keyboard
echo G e t - C o | ./hid-gadget-test /dev/hidg2 keyboard
echo m a n d | ./hid-gadget-test /dev/hidg2 keyboard
sleep 0.8
echo left-meta r | ./hid-gadget-test /dev/hidg2 keyboard
sleep 0.3
echo c m d | ./hid-gadget-test /dev/hidg2 keyboard
echo enter  | ./hid-gadget-test /dev/hidg2 keyboard
echo s h u t | ./hid-gadget-test /dev/hidg2 keyboard
echo d o w n | ./hid-gadget-test /dev/hidg2 keyboard
echo space | ./hid-gadget-test /dev/hidg2 keyboard
echo / s | ./hid-gadget-test /dev/hidg2 keyboard
echo space | ./hid-gadget-test /dev/hidg2 keyboard
echo / t | ./hid-gadget-test /dev/hidg2 keyboard
echo space | ./hid-gadget-test /dev/hidg2 keyboard
echo 0 | ./hid-gadget-test /dev/hidg2 keyboard
echo enter | ./hid-gadget-test /dev/hidg2 keyboard

